# Generated by Django 2.1.7 on 2019-04-24 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20190425_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='description',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(upload_to='teachers/'),
        ),
    ]
