# Generated by Django 2.1.7 on 2019-04-24 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20190425_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='fio',
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='', max_length=40, verbose_name='Ф.И.О'),
            preserve_default=False,
        ),
    ]
