# Generated by Django 2.1.7 on 2019-04-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20190425_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(upload_to='static/media/teachers/'),
        ),
    ]
