# Generated by Django 2.1.7 on 2019-05-08 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_auto_20190508_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Teacher',
        ),
    ]
