# Generated by Django 2.1.7 on 2019-05-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_remove_teacher_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Discipline',
        ),
        migrations.AddField(
            model_name='teacher',
            name='discipline',
            field=models.ManyToManyField(help_text='Select a discipline for this teacher', to='mysite.Discipline'),
        ),
    ]
