# Generated by Django 2.1.7 on 2019-05-27 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_auto_20190515_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='last_name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='Ф.И.О'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='img',
            field=models.ImageField(blank=True, default='avatars/empty.jpg', null=True, upload_to='avatars/'),
        ),
    ]
