# Generated by Django 2.1.7 on 2019-05-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_auto_20190528_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='position',
            field=models.CharField(default='', max_length=100, verbose_name='Должность'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teacher',
            name='discipline',
            field=models.ManyToManyField(help_text='Select a discipline for this teacher', to='mysite.Discipline', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='img',
            field=models.ImageField(blank=True, default='avatars/empty.jpg', null=True, upload_to='avatars/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='summary',
            field=models.TextField(help_text='Enter a brief description of the Teacher', max_length=1000, verbose_name='Детальная информация'),
        ),
    ]
